"""Add trending period columns

Revision ID: d9f11015f27a
Revises: 
Create Date: 2025-03-20 03:04:05.436666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = 'd9f11015f27a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add new columns as nullable
    op.add_column('daily_trending_repos', sa.Column('trending_date', sa.Date(), nullable=True))
    op.add_column('monthly_trending_repos', sa.Column('trending_month', sa.Integer(), nullable=True))
    op.add_column('weekly_trending_repos', sa.Column('trending_week', sa.Integer(), nullable=True))

    # Step 2: Update existing rows with appropriate values
    op.execute(
        f"UPDATE daily_trending_repos SET trending_date = '{datetime.now().date()}' WHERE trending_date IS NULL"
    )
    op.execute(
        f"UPDATE monthly_trending_repos SET trending_month = {datetime.now().month} WHERE trending_month IS NULL"
    )
    op.execute(
        f"UPDATE weekly_trending_repos SET trending_week = {datetime.now().isocalendar()[1]} WHERE trending_week IS NULL"
    )

    # Step 3: Alter columns to be non-nullable
    op.alter_column('daily_trending_repos', 'trending_date', nullable=False)
    op.alter_column('monthly_trending_repos', 'trending_month', nullable=False)
    op.alter_column('weekly_trending_repos', 'trending_week', nullable=False)

    # Alter existing date columns to DateTime
    op.alter_column('daily_trending_repos', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('monthly_trending_repos', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('weekly_trending_repos', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_trending_repos', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('weekly_trending_repos', 'trending_week')
    op.alter_column('monthly_trending_repos', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('monthly_trending_repos', 'trending_month')
    op.alter_column('daily_trending_repos', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('daily_trending_repos', 'trending_date')
    # ### end Alembic commands ###